version: "3.7"
services:
  RAG:
    build: .
    container_name: RAG_QNA
    restart: always
    environment:
      - LLM_TYPE: Ollama_mistral:latest
      - OPENAI_API_KEY: None
      - OLLAMA_BASE_URL: http://ollama-container:11434
    ports:
      - 8500:8500
  ollama-container:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434